//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: BridgeChat.proto
namespace BridgeChat.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModuleIntro")]
  public partial class ModuleIntro : global::ProtoBuf.IExtensible
  {
    public ModuleIntro() {}
    
    private string _longName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"long_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LongName
    {
      get { return _longName; }
      set { _longName = value; }
    }
    private string _shortName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"short_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ShortName
    {
      get { return _shortName; }
      set { _shortName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BindingRequest")]
  public partial class BindingRequest : global::ProtoBuf.IExtensible
  {
    public BindingRequest() {}
    
    private string _bindInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bind_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string BindInfo
    {
      get { return _bindInfo; }
      set { _bindInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BindingResponse")]
  public partial class BindingResponse : global::ProtoBuf.IExtensible
  {
    public BindingResponse() {}
    
    private bool _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Success
    {
      get { return _success; }
      set { _success = value; }
    }
    private string _diagnostic;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"diagnostic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Diagnostic
    {
      get { return _diagnostic?? ""; }
      set { _diagnostic = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DiagnosticSpecified
    {
      get { return this._diagnostic != null; }
      set { if (value == (this._diagnostic== null)) this._diagnostic = value ? this.Diagnostic : (string)null; }
    }
    private bool ShouldSerializeDiagnostic() { return DiagnosticSpecified; }
    private void ResetDiagnostic() { DiagnosticSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnbindRequest")]
  public partial class UnbindRequest : global::ProtoBuf.IExtensible
  {
    public UnbindRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserStatus")]
  public partial class UserStatus : global::ProtoBuf.IExtensible
  {
    public UserStatus() {}
    
    private bool? _onlineStatus;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"online_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool OnlineStatus
    {
      get { return _onlineStatus?? default(bool); }
      set { _onlineStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool OnlineStatusSpecified
    {
      get { return this._onlineStatus != null; }
      set { if (value == (this._onlineStatus== null)) this._onlineStatus = value ? this.OnlineStatus : (bool?)null; }
    }
    private bool ShouldSerializeOnlineStatus() { return OnlineStatusSpecified; }
    private void ResetOnlineStatus() { OnlineStatusSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserEvent")]
  public partial class UserEvent : global::ProtoBuf.IExtensible
  {
    public UserEvent() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _pluginId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"plugin_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PluginId
    {
      get { return _pluginId?? ""; }
      set { _pluginId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool PluginIdSpecified
    {
      get { return this._pluginId != null; }
      set { if (value == (this._pluginId== null)) this._pluginId = value ? this.PluginId : (string)null; }
    }
    private bool ShouldSerializePluginId() { return PluginIdSpecified; }
    private void ResetPluginId() { PluginIdSpecified = false; }
    
    private UserStatus _userStatus = null;
    [global::ProtoBuf.ProtoMember(101, IsRequired = false, Name=@"user_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UserStatus UserStatus
    {
      get { return _userStatus; }
      set { _userStatus = value; }
    }
    private string _chatMessage;
    [global::ProtoBuf.ProtoMember(102, IsRequired = false, Name=@"chat_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ChatMessage
    {
      get { return _chatMessage?? ""; }
      set { _chatMessage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ChatMessageSpecified
    {
      get { return this._chatMessage != null; }
      set { if (value == (this._chatMessage== null)) this._chatMessage = value ? this.ChatMessage : (string)null; }
    }
    private bool ShouldSerializeChatMessage() { return ChatMessageSpecified; }
    private void ResetChatMessage() { ChatMessageSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GroupStatus")]
  public partial class GroupStatus : global::ProtoBuf.IExtensible
  {
    public GroupStatus() {}
    
    private string _topic;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"topic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Topic
    {
      get { return _topic?? ""; }
      set { _topic = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TopicSpecified
    {
      get { return this._topic != null; }
      set { if (value == (this._topic== null)) this._topic = value ? this.Topic : (string)null; }
    }
    private bool ShouldSerializeTopic() { return TopicSpecified; }
    private void ResetTopic() { TopicSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GroupMessage")]
  public partial class GroupMessage : global::ProtoBuf.IExtensible
  {
    public GroupMessage() {}
    
    private uint _groupId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GroupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private BindingRequest _bindingRequest = null;
    [global::ProtoBuf.ProtoMember(101, IsRequired = false, Name=@"binding_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BindingRequest BindingRequest
    {
      get { return _bindingRequest; }
      set { _bindingRequest = value; }
    }
    private BindingResponse _bindingResponse = null;
    [global::ProtoBuf.ProtoMember(102, IsRequired = false, Name=@"binding_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BindingResponse BindingResponse
    {
      get { return _bindingResponse; }
      set { _bindingResponse = value; }
    }
    private UnbindRequest _unbindRequest = null;
    [global::ProtoBuf.ProtoMember(103, IsRequired = false, Name=@"unbind_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UnbindRequest UnbindRequest
    {
      get { return _unbindRequest; }
      set { _unbindRequest = value; }
    }
    private GroupStatus _groupStatusChange = null;
    [global::ProtoBuf.ProtoMember(104, IsRequired = false, Name=@"group_status_change", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GroupStatus GroupStatusChange
    {
      get { return _groupStatusChange; }
      set { _groupStatusChange = value; }
    }
    private UserEvent _userEvent = null;
    [global::ProtoBuf.ProtoMember(105, IsRequired = false, Name=@"user_event", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UserEvent UserEvent
    {
      get { return _userEvent; }
      set { _userEvent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}