# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BridgeChat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BridgeChat.proto',
  package='',
  serialized_pb='\n\x10\x42ridgeChat.proto\"\x99\x01\n\x0bModuleIntro\x12\x11\n\tlong_name\x18\x01 \x02(\t\x12\x12\n\nshort_name\x18\x02 \x02(\t\x12!\n\x12supports_plaintext\x18\x64 \x01(\x08:\x05\x66\x61lse\x12\x1c\n\rsupports_html\x18\x65 \x01(\x08:\x05\x66\x61lse\x12\"\n\x13supports_image_link\x18\x66 \x01(\x08:\x05\x66\x61lse\"#\n\x0e\x42indingRequest\x12\x11\n\tbind_info\x18\x01 \x02(\t\"6\n\x0f\x42indingResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x12\n\ndiagnostic\x18\x02 \x01(\t\"\x0f\n\rUnbindRequest\"#\n\nUserStatus\x12\x15\n\ronline_status\x18\x02 \x01(\x08\"v\n\tUserEvent\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x11\n\tplugin_id\x18\x02 \x01(\t\x12 \n\x0buser_status\x18\x65 \x01(\x0b\x32\x0b.UserStatus\x12\"\n\x0c\x63hat_message\x18\x66 \x01(\x0b\x32\x0c.ChatMessage\"B\n\x0b\x43hatMessage\x12\x11\n\tplaintext\x18\x01 \x01(\t\x12\x0c\n\x04html\x18\x02 \x01(\t\x12\x12\n\nimage_link\x18\x03 \x01(\t\"\x1c\n\x0bGroupStatus\x12\r\n\x05topic\x18\x01 \x01(\t\"\xe9\x01\n\x0cGroupMessage\x12\x10\n\x08group_id\x18\x01 \x02(\r\x12(\n\x0f\x62inding_request\x18\x65 \x01(\x0b\x32\x0f.BindingRequest\x12*\n\x10\x62inding_response\x18\x66 \x01(\x0b\x32\x10.BindingResponse\x12&\n\x0eunbind_request\x18g \x01(\x0b\x32\x0e.UnbindRequest\x12)\n\x13group_status_change\x18h \x01(\x0b\x32\x0c.GroupStatus\x12\x1e\n\nuser_event\x18i \x01(\x0b\x32\n.UserEvent')




_MODULEINTRO = _descriptor.Descriptor(
  name='ModuleIntro',
  full_name='ModuleIntro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='long_name', full_name='ModuleIntro.long_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='short_name', full_name='ModuleIntro.short_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='supports_plaintext', full_name='ModuleIntro.supports_plaintext', index=2,
      number=100, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='supports_html', full_name='ModuleIntro.supports_html', index=3,
      number=101, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='supports_image_link', full_name='ModuleIntro.supports_image_link', index=4,
      number=102, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=174,
)


_BINDINGREQUEST = _descriptor.Descriptor(
  name='BindingRequest',
  full_name='BindingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bind_info', full_name='BindingRequest.bind_info', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=176,
  serialized_end=211,
)


_BINDINGRESPONSE = _descriptor.Descriptor(
  name='BindingResponse',
  full_name='BindingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='BindingResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diagnostic', full_name='BindingResponse.diagnostic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=213,
  serialized_end=267,
)


_UNBINDREQUEST = _descriptor.Descriptor(
  name='UnbindRequest',
  full_name='UnbindRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=269,
  serialized_end=284,
)


_USERSTATUS = _descriptor.Descriptor(
  name='UserStatus',
  full_name='UserStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='online_status', full_name='UserStatus.online_status', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=286,
  serialized_end=321,
)


_USEREVENT = _descriptor.Descriptor(
  name='UserEvent',
  full_name='UserEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='UserEvent.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='plugin_id', full_name='UserEvent.plugin_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_status', full_name='UserEvent.user_status', index=2,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chat_message', full_name='UserEvent.chat_message', index=3,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=323,
  serialized_end=441,
)


_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plaintext', full_name='ChatMessage.plaintext', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='html', full_name='ChatMessage.html', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_link', full_name='ChatMessage.image_link', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=443,
  serialized_end=509,
)


_GROUPSTATUS = _descriptor.Descriptor(
  name='GroupStatus',
  full_name='GroupStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='GroupStatus.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=511,
  serialized_end=539,
)


_GROUPMESSAGE = _descriptor.Descriptor(
  name='GroupMessage',
  full_name='GroupMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_id', full_name='GroupMessage.group_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='binding_request', full_name='GroupMessage.binding_request', index=1,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='binding_response', full_name='GroupMessage.binding_response', index=2,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unbind_request', full_name='GroupMessage.unbind_request', index=3,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group_status_change', full_name='GroupMessage.group_status_change', index=4,
      number=104, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_event', full_name='GroupMessage.user_event', index=5,
      number=105, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=542,
  serialized_end=775,
)

_USEREVENT.fields_by_name['user_status'].message_type = _USERSTATUS
_USEREVENT.fields_by_name['chat_message'].message_type = _CHATMESSAGE
_GROUPMESSAGE.fields_by_name['binding_request'].message_type = _BINDINGREQUEST
_GROUPMESSAGE.fields_by_name['binding_response'].message_type = _BINDINGRESPONSE
_GROUPMESSAGE.fields_by_name['unbind_request'].message_type = _UNBINDREQUEST
_GROUPMESSAGE.fields_by_name['group_status_change'].message_type = _GROUPSTATUS
_GROUPMESSAGE.fields_by_name['user_event'].message_type = _USEREVENT
DESCRIPTOR.message_types_by_name['ModuleIntro'] = _MODULEINTRO
DESCRIPTOR.message_types_by_name['BindingRequest'] = _BINDINGREQUEST
DESCRIPTOR.message_types_by_name['BindingResponse'] = _BINDINGRESPONSE
DESCRIPTOR.message_types_by_name['UnbindRequest'] = _UNBINDREQUEST
DESCRIPTOR.message_types_by_name['UserStatus'] = _USERSTATUS
DESCRIPTOR.message_types_by_name['UserEvent'] = _USEREVENT
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['GroupStatus'] = _GROUPSTATUS
DESCRIPTOR.message_types_by_name['GroupMessage'] = _GROUPMESSAGE

class ModuleIntro(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODULEINTRO

  # @@protoc_insertion_point(class_scope:ModuleIntro)

class BindingRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BINDINGREQUEST

  # @@protoc_insertion_point(class_scope:BindingRequest)

class BindingResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BINDINGRESPONSE

  # @@protoc_insertion_point(class_scope:BindingResponse)

class UnbindRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNBINDREQUEST

  # @@protoc_insertion_point(class_scope:UnbindRequest)

class UserStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERSTATUS

  # @@protoc_insertion_point(class_scope:UserStatus)

class UserEvent(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USEREVENT

  # @@protoc_insertion_point(class_scope:UserEvent)

class ChatMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHATMESSAGE

  # @@protoc_insertion_point(class_scope:ChatMessage)

class GroupStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GROUPSTATUS

  # @@protoc_insertion_point(class_scope:GroupStatus)

class GroupMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GROUPMESSAGE

  # @@protoc_insertion_point(class_scope:GroupMessage)


# @@protoc_insertion_point(module_scope)
